package es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas;

import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.acciones.AccionesBajaClientes;
import es.seas.unidad3.ejemplo.fastfoodcompany.principal.Conexion;
import es.seas.unidad3.ejemplo.fastfoodcompany.principal.FastFoodCompanyFrame;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 * Clase con el panel de baja de clientes. El alumno deberá completar la clase
 * de cara al ejercicio feedback.
 *
 * @author
 */
public class PanelBajaClientes extends javax.swing.JPanel {

    private FastFoodCompanyFrame frame;
    private AccionesBajaClientes acciones;
    DefaultListModel modelo = new DefaultListModel();

    public PanelBajaClientes() {
        this.frame = frame;
        initComponents();
        listarClientes();
        acciones = new AccionesBajaClientes(this);

    }

    private void listarClientes() {
        Conexion conexion = new Conexion();
        conexion.connect();
        modelo.clear();
        ArrayList<String> clientes = conexion.getClientes();
        for (int i = 0; i < clientes.size(); i++) {
            modelo.addElement(clientes.get(i));;
        }

        lstClientes.setModel(modelo);
    }

    public FastFoodCompanyFrame getFrame() {
        return frame;
    }

    public void setFrame(FastFoodCompanyFrame frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiResultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(null);

        etiResultado.setText("jLabel1");
        add(etiResultado);
        etiResultado.setBounds(0, 0, 0, 0);

        lstClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstClientes);

        add(jScrollPane1);
        jScrollPane1.setBounds(22, 20, 330, 160);

        jLabel1.setText("no hay acciones");
        add(jLabel1);
        jLabel1.setBounds(30, 220, 270, 40);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar);
        btnEliminar.setBounds(260, 190, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (lstClientes.getSelectedIndex() == -1) {
            jLabel1.setText("No hay un cliente seleccionado para eliminar");
        } else {
            String str = lstClientes.getSelectedValue().toString();
            String[] list = str.split(" ");
            acciones.eliminarCliente(list[0], list[1]);
            jLabel1.setText("Cliente Eliminado");
            listarClientes();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel etiResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstClientes;
    // End of variables declaration//GEN-END:variables
}
