package es.seas.unidad3.ejemplo.fastfoodcompany.clientes.vistas;

import es.seas.unidad3.ejemplo.fastfoodcompany.clientes.acciones.AccionesAltaClientes;
import es.seas.unidad3.ejemplo.fastfoodcompany.principal.FastFoodCompanyFrame;
import javax.swing.JTextField;

/**
 * Clase con el panel de alta de clientes.
 *
 * @author
 */
public class PanelAltaClientes extends javax.swing.JPanel {

    private FastFoodCompanyFrame frame;
    private AccionesAltaClientes acciones;

    /**
     * Constructor del PanelAltaClientes
     *
     * @param frame FastFoodCompanyFrame ventana en la que se mostrará el panel.
     */
    public PanelAltaClientes(FastFoodCompanyFrame frame) {
        this.frame = frame;
        initComponents();
        acciones = new AccionesAltaClientes(this);
    }

    /**
     * Getter de la ventana.
     *
     * @return FastFoodCompanyFrame frame.
     */
    public FastFoodCompanyFrame getFrame() {
        return frame;
    }

    /**
     * Setter de la ventana.
     *
     * @param frame FastFoodCompanyFrame ventana.
     */
    public void setFrame(FastFoodCompanyFrame frame) {
        this.frame = frame;
    }

    /**
     * Getter del campo de texto del nombre.
     *
     * @return JTextField txtNombre.
     */
    public JTextField getTxtNombre() {
        return txtNombre;
    }

    /**
     * Getter del campo de texto del apellido1.
     *
     * @return JTextField txtApellido2.
     */
    public JTextField getTxtApellido1() {
        return txtApellido1;
    }

    /**
     * Getter del campo de texto del apellido2.
     *
     * @return JTextField txtApellido2.
     */
    public JTextField getTxtApellido2() {
        return txtApellido2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblEstaGuardado = new javax.swing.JLabel();

        setLayout(null);

        lblNombre.setText("Nombre:");
        add(lblNombre);
        lblNombre.setBounds(50, 40, 90, 20);

        lblApellido1.setText("Apellido 1:");
        add(lblApellido1);
        lblApellido1.setBounds(50, 80, 90, 20);

        lblApellido2.setText("Apellido 2:");
        add(lblApellido2);
        lblApellido2.setBounds(50, 120, 90, 20);
        add(txtNombre);
        txtNombre.setBounds(150, 40, 180, 22);
        add(txtApellido1);
        txtApellido1.setBounds(150, 80, 180, 22);
        add(txtApellido2);
        txtApellido2.setBounds(150, 120, 180, 22);

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(252, 160, 80, 23);
        add(lblEstaGuardado);
        lblEstaGuardado.setBounds(130, 190, 190, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        boolean isSaved = acciones.guardarCliente();
        if (isSaved) {
            lblEstaGuardado.setText("CLIENTE GUARDADO");
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblEstaGuardado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
